//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.reidemeister.wp.CalendarTemplates.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.reidemeister.wp.CalendarTemplates.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add template ähnelt.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die templates ähnelt.
        /// </summary>
        public static string AllTemplates {
            get {
                return ResourceManager.GetString("AllTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CALENDAR TEMPLATES ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Any unsaved changes will be lost! ähnelt.
        /// </summary>
        public static string EditConfirmExitDescr {
            get {
                return ResourceManager.GetString("EditConfirmExitDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved changes! ähnelt.
        /// </summary>
        public static string EditConfirmExitTitle {
            get {
                return ResourceManager.GetString("EditConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit template ähnelt.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End (offset to start) ähnelt.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die help ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you like the app consider giving me a donation via IAP. The money will help me to continue supporting the app. ähnelt.
        /// </summary>
        public static string HelpDonation {
            get {
                return ResourceManager.GetString("HelpDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big ähnelt.
        /// </summary>
        public static string HelpDonationBig {
            get {
                return ResourceManager.GetString("HelpDonationBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string HelpDonationMedium {
            get {
                return ResourceManager.GetString("HelpDonationMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small ähnelt.
        /// </summary>
        public static string HelpDonationSmall {
            get {
                return ResourceManager.GetString("HelpDonationSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Calendar Templates&quot; allows to define templates to quickly create appointments in your calendar. You can pin those templates as tiles to the start screen. ähnelt.
        /// </summary>
        public static string HelpIntro {
            get {
                return ResourceManager.GetString("HelpIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can contact me via the following address for questions, feedback, enhancements or problems. ähnelt.
        /// </summary>
        public static string HelpSupportDescr1 {
            get {
                return ResourceManager.GetString("HelpSupportDescr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please note that it is not possible to reply to comments in the store. ähnelt.
        /// </summary>
        public static string HelpSupportDescr2 {
            get {
                return ResourceManager.GetString("HelpSupportDescr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SUPPORT ähnelt.
        /// </summary>
        public static string HelpSupportHeader {
            get {
                return ResourceManager.GetString("HelpSupportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die help ähnelt.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon + Name ähnelt.
        /// </summary>
        public static string IconAndName {
            get {
                return ResourceManager.GetString("IconAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can create templates via the &quot;add&quot;-button on the main page.
        ///On the new page set all properties you want to set for your appointments. The icon and name are only used in this app and will not appear in the calendar. You can leave any textfield empty when you don&apos;t need it.
        ///
        ///To edit an existing template tap and hold in the list and choose the &quot;edit&quot; menu. ähnelt.
        /// </summary>
        public static string InfoCreateDescr {
            get {
                return ResourceManager.GetString("InfoCreateDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TEMPLATES ähnelt.
        /// </summary>
        public static string InfoCreateHeader {
            get {
                return ResourceManager.GetString("InfoCreateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To run a template simply tap on it in the main page. A new appointment with all properties from the template will be created. You will see all values in the regular calendar app and you have to save the appointment there.
        ///
        ///You can also pin templates to the start screen (hold for the menu). Tapping the tile will directly create the new appointment. ähnelt.
        /// </summary>
        public static string InfoRunDescr {
            get {
                return ResourceManager.GetString("InfoRunDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RUN TEMPLATES ähnelt.
        /// </summary>
        public static string InfoRunHeader {
            get {
                return ResourceManager.GetString("InfoRunHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die templates ähnelt.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pin tile to start ähnelt.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rate in the Store ähnelt.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder ähnelt.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no reminder ähnelt.
        /// </summary>
        public static string Reminder0 {
            get {
                return ResourceManager.GetString("Reminder0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die at start time ähnelt.
        /// </summary>
        public static string Reminder1 {
            get {
                return ResourceManager.GetString("Reminder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5 minutes ähnelt.
        /// </summary>
        public static string Reminder2 {
            get {
                return ResourceManager.GetString("Reminder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 minutes ähnelt.
        /// </summary>
        public static string Reminder3 {
            get {
                return ResourceManager.GetString("Reminder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 15 minutes ähnelt.
        /// </summary>
        public static string Reminder4 {
            get {
                return ResourceManager.GetString("Reminder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 30 minutes ähnelt.
        /// </summary>
        public static string Reminder5 {
            get {
                return ResourceManager.GetString("Reminder5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 hour ähnelt.
        /// </summary>
        public static string Reminder6 {
            get {
                return ResourceManager.GetString("Reminder6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 18 hours ähnelt.
        /// </summary>
        public static string Reminder7 {
            get {
                return ResourceManager.GetString("Reminder7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 day ähnelt.
        /// </summary>
        public static string Reminder8 {
            get {
                return ResourceManager.GetString("Reminder8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 week ähnelt.
        /// </summary>
        public static string Reminder9 {
            get {
                return ResourceManager.GetString("Reminder9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die finished ähnelt.
        /// </summary>
        public static string RunDescr {
            get {
                return ResourceManager.GetString("RunDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft does not provide a way to close the app. Please use the back button. ähnelt.
        /// </summary>
        public static string RunNote {
            get {
                return ResourceManager.GetString("RunNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start (day is always the current day) ähnelt.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die free ähnelt.
        /// </summary>
        public static string Status0 {
            get {
                return ResourceManager.GetString("Status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tentative ähnelt.
        /// </summary>
        public static string Status1 {
            get {
                return ResourceManager.GetString("Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die busy ähnelt.
        /// </summary>
        public static string Status2 {
            get {
                return ResourceManager.GetString("Status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die out of office ähnelt.
        /// </summary>
        public static string Status3 {
            get {
                return ResourceManager.GetString("Status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thanks! ähnelt.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die current time ähnelt.
        /// </summary>
        public static string Time0 {
            get {
                return ResourceManager.GetString("Time0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fixed time ähnelt.
        /// </summary>
        public static string Time1 {
            get {
                return ResourceManager.GetString("Time1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die current time + offset ähnelt.
        /// </summary>
        public static string Time2 {
            get {
                return ResourceManager.GetString("Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all day ähnelt.
        /// </summary>
        public static string Time3 {
            get {
                return ResourceManager.GetString("Time3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die remove tile from start ähnelt.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die version  ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
